from colorama import *
print(Fore . GREEN, Back . CYAN)
print(  "             *             ")
print( "           *    *           " )
print(  "         *       *           " )
print(  "        *         *           " )
print(  "       *           *           " )
print(  "      *             *         "   )
print(  "     *               *        "    )
print(  "    *                 *       "     )
print(  "   *                   *       "     )
print(  "  *                     *      "      )
print( "  *                       *     "       )
print( " *                         *    "        )
print( " ****************************     "          )