from colorama import *
print(Fore.WHITE,Back.RED)
print("                             **********************************                                                            ")
print("                            *                                  *                                            ")
print("                           *                                  *                                            ")
print("                          *                                  *                                             ")
print("                         *                                  *                                              ")
print("                        *                                  *                                               ")
print("                       *                                  *                                                ")
print("                      *                                  *                                                 ")
print("                     *                                  *                                                  ")
print("                    *                                  *                                                  ")
print("                   ************************************                                                                                   ")