from colorama import *
print(Fore.MAGENTA,Back.YELLOW)
print("                       *********                                                ")
print("                    **           **                                                   ")
print("                  **               **                                                      ")
print("                 **                 **                                                      ")
print("               **                     **                                                     ")
print("                 **                 **                                                      ")
print("                   **             **                                                      ")
print("                     **         **                                                      ")
print("                       **********                                              ")